### ISSUE TITLE
Fix: build failure due to dependency on lib modules 

### ISSUE THREAD

**Issue by harishanand95** [Open-UAV/openuav-playground#15]
Fix involves having the lib modules available in lib package
`mkdir /openuav-playground/openuav-app/dockerfiles/openuav_sample/lib`

`cp -r /lib/modules/$(uname -r) /openuav-playground/openuav-app/dockerfiles/openuav_sample/lib`

**Comment by harishanand95** [comment]
@darknight-007 
https://github.com/intel-ros/realsense/issues/388#issuecomment-410672421

**Comment by harishanand95** [comment]
we could have `/lib/modules` in docker to be a mapped volume to host machine's `/lib/modules/`

**Comment by rjunk** [comment]
There doesnt seem to be any way to mount outside of the build context - https://github.com/moby/moby/issues/3156#issue-24060480
I also tried installing the headers during the build like (https://github.com/Open-UAV/openuav-playground/issues/15?_pjax=%23js-repo-pjax-container#issuecomment-438951005), but it still failed on the uvcvideo check

**Comment by harishanand95** [comment]
@rjunk @darknight-007 

> Errors were encountered while processing:
 ros-kinetic-librealsense
 ros-kinetic-realsense-camera
 ros-kinetic-turtlebot-bringup
 ros-kinetic-turtlebot-teleop
 ros-kinetic-turtlebot
 ros-kinetic-turtlebot-actions
 ros-kinetic-turtlebot-calibration
 ros-kinetic-turtlebot-follower
 ros-kinetic-turtlebot-navigation
 ros-kinetic-turtlebot-rapps
 ros-kinetic-turtlebot-apps
 ros-kinetic-turtlebot-gazebo
 ros-kinetic-turtlebot-stage
 ros-kinetic-turtlebot-stdr
 ros-kinetic-turtlebot-simulator
E: Sub-process /usr/bin/dpkg returned an error code (1)


From my understanding of what the issue is.
Failure happens when we try to install `ros-kinetic-librealsense` inside the container. This package checks for kernel module `uvcvideo` and it was missing in the host machine. I have installed it for the kernel 4.15 in our machine. It still fails to find this kernel module. I am still not sure how it worked first time.
 (https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md)

**Comment by harishanand95** [comment]
Closing the issue for now
