### ISSUE TITLE
QUESTION&ANSWAER

### ISSUE THREAD

**Issue by AdamLouis123456** [Open-UAV/openuav-playground#21]
heyyyyy, i wanna ask you guys if this openuav-playground project should be runned in a server equipt with GPU?

**Comment by darknight-007** [comment]
Hi Adam, 

Ideally yes, we do the camera rendering in Gazebo through shared X server, that is running on the host. Having a good graphics card helps especially when emulating cameras on multiple drones. However, you don't need Deep-learning-grade GPUs.
