### ISSUE TITLE
Build error due to Postgresql 9.6 in web container

### ISSUE THREAD

**Issue by harishanand95** [Open-UAV/openuav-playground#7]
https://github.com/Open-UAV/openuav-playground/blob/526ae5690144c9ab4dd58071bf10a5f84bf996f3/openuav-app/dockerfiles/django/Dockerfile#L11

**Comment by harishanand95** [comment]
9.6 version is not there in the python 3 `FROM python:3` image (based on ubuntu 16.04) we use for django. A fresh build fails to fetch package postgresql-client-9.6.

**Comment by rjunk** [comment]
I have the opposite occurring, switching back to 9.4 fails to fetch the package.

**Comment by harishanand95** [comment]
Weird, let me give it a try using `build --no-cache`

**Comment by harishanand95** [comment]
> $ docker-compose build --no-cache web
WARNING: The DISPLAY variable is not set. Defaulting to a blank string.
Building web
Step 1/14 : FROM python:3
 ---> d21927554614
Step 2/14 : ENV PYTHONUNBUFFERED 1
 ---> Running in f22a8ee0c328
 ---> 11c5d56957fd
Removing intermediate container f22a8ee0c328
Step 3/14 : RUN mkdir /code
 ---> Running in de3d43c8a49c
 ---> 0202081184d4
Removing intermediate container de3d43c8a49c
Step 4/14 : WORKDIR /code
 ---> 10ff80d5bb48
Removing intermediate container a14d52d6b0d7
Step 5/14 : ADD requirements.txt /code/
 ---> 566c327d54ee
Removing intermediate container 72b5168d8815
Step 6/14 : RUN apt-get update
 ---> Running in 5b76cd49f929
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Get:4 http://deb.debian.org jessie Release [148 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [679 kB]
Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [23.0 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 7s (1295 kB/s)
Reading package lists...
 ---> 61b371f554db
Removing intermediate container 5b76cd49f929
Step 7/14 : RUN pip install -r requirements.txt
 ---> Running in 6cbe71d7f9c6
Collecting Django==2.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/44/98/35b935a98a17e9a188efc2d53fc51ae0c8bf498a77bc224f9321ae5d111c/Django-2.0-py3-none-any.whl (7.1MB)
Collecting gunicorn==19.7.1 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/64/32/becbd4089a4c06f0f9f538a76e9fe0b19a08f010bcb47dcdbfbc640cdf7d/gunicorn-19.7.1-py2.py3-none-any.whl (111kB)
Collecting psycopg2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/5e/d0/9e2b3ed43001ebed45caf56d5bb9d44ed3ebd68e12b87845bfa7bcd46250/psycopg2-2.7.5-cp36-cp36m-manylinux1_x86_64.whl (2.7MB)
Collecting pytz (from Django==2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
Installing collected packages: pytz, Django, gunicorn, psycopg2
Successfully installed Django-2.0 gunicorn-19.7.1 psycopg2-2.7.5 pytz-2018.5
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 1e2470e1090a
Removing intermediate container 6cbe71d7f9c6
Step 8/14 : RUN apt-get install -y vim
 ---> Running in bc54bfe6db8e
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libgpm2 vim-common vim-runtime
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-common vim-runtime
0 upgraded, 4 newly installed, 0 to remove and 73 not upgraded.
Need to get 6219 kB of archives.
After this operation, 28.9 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main libgpm2 amd64 1.20.4-6.1+b2 [34.0 kB]
Get:2 http://deb.debian.org/debian/ jessie/main vim-common amd64 2:7.4.488-7+deb8u3 [185 kB]
Get:3 http://deb.debian.org/debian/ jessie/main vim-runtime all 2:7.4.488-7+deb8u3 [5048 kB]
Get:4 http://deb.debian.org/debian/ jessie/main vim amd64 2:7.4.488-7+deb8u3 [953 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 6219 kB in 1s (3869 kB/s)
Selecting previously unselected package libgpm2:amd64.
(Reading database ... 21636 files and directories currently installed.)
Preparing to unpack .../libgpm2_1.20.4-6.1+b2_amd64.deb ...
Unpacking libgpm2:amd64 (1.20.4-6.1+b2) ...
Selecting previously unselected package vim-common.
Preparing to unpack .../vim-common_2%3a7.4.488-7+deb8u3_amd64.deb ...
Unpacking vim-common (2:7.4.488-7+deb8u3) ...
Selecting previously unselected package vim-runtime.
Preparing to unpack .../vim-runtime_2%3a7.4.488-7+deb8u3_all.deb ...
Adding 'diversion of /usr/share/vim/vim74/doc/help.txt to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim74/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:7.4.488-7+deb8u3) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a7.4.488-7+deb8u3_amd64.deb ...
Unpacking vim (2:7.4.488-7+deb8u3) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Setting up libgpm2:amd64 (1.20.4-6.1+b2) ...
Setting up vim-common (2:7.4.488-7+deb8u3) ...
Setting up vim-runtime (2:7.4.488-7+deb8u3) ...
Processing /usr/share/vim/addons/doc
Setting up vim (2:7.4.488-7+deb8u3) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
Processing triggers for libc-bin (2.19-18+deb8u10) ...
 ---> 0b81235536df
Removing intermediate container bc54bfe6db8e
Step 9/14 : RUN apt-get install -y dnsutils
 ---> Running in 85403b684b48
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  bind9-host libbind9-90 libdns100 libisc95 libisccc90 libisccfg90 liblwres90
Suggested packages:
  rblcheck
The following NEW packages will be installed:
  bind9-host dnsutils libbind9-90 libdns100 libisc95 libisccc90 libisccfg90
  liblwres90
0 upgraded, 8 newly installed, 0 to remove and 73 not upgraded.
Need to get 1233 kB of archives.
After this operation, 3571 kB of additional disk space will be used.
Get:1 http://security.debian.org/ jessie/updates/main libisc95 amd64 1:9.9.5.dfsg-9+deb8u16 [170 kB]
Get:2 http://security.debian.org/ jessie/updates/main libdns100 amd64 1:9.9.5.dfsg-9+deb8u16 [682 kB]
Get:3 http://security.debian.org/ jessie/updates/main libisccc90 amd64 1:9.9.5.dfsg-9+deb8u16 [37.4 kB]
Get:4 http://security.debian.org/ jessie/updates/main libisccfg90 amd64 1:9.9.5.dfsg-9+deb8u16 [57.9 kB]
Get:5 http://security.debian.org/ jessie/updates/main libbind9-90 amd64 1:9.9.5.dfsg-9+deb8u16 [44.2 kB]
Get:6 http://security.debian.org/ jessie/updates/main liblwres90 amd64 1:9.9.5.dfsg-9+deb8u16 [53.9 kB]
Get:7 http://security.debian.org/ jessie/updates/main bind9-host amd64 1:9.9.5.dfsg-9+deb8u16 [68.4 kB]
Get:8 http://security.debian.org/ jessie/updates/main dnsutils amd64 1:9.9.5.dfsg-9+deb8u16 [120 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1233 kB in 0s (6618 kB/s)
Selecting previously unselected package libisc95.
(Reading database ... 23367 files and directories currently installed.)
Preparing to unpack .../libisc95_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking libisc95 (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package libdns100.
Preparing to unpack .../libdns100_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking libdns100 (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package libisccc90.
Preparing to unpack .../libisccc90_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking libisccc90 (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package libisccfg90.
Preparing to unpack .../libisccfg90_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking libisccfg90 (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package libbind9-90.
Preparing to unpack .../libbind9-90_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking libbind9-90 (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package liblwres90.
Preparing to unpack .../liblwres90_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking liblwres90 (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package bind9-host.
Preparing to unpack .../bind9-host_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking bind9-host (1:9.9.5.dfsg-9+deb8u16) ...
Selecting previously unselected package dnsutils.
Preparing to unpack .../dnsutils_1%3a9.9.5.dfsg-9+deb8u16_amd64.deb ...
Unpacking dnsutils (1:9.9.5.dfsg-9+deb8u16) ...
Setting up libisc95 (1:9.9.5.dfsg-9+deb8u16) ...
Setting up libdns100 (1:9.9.5.dfsg-9+deb8u16) ...
Setting up libisccc90 (1:9.9.5.dfsg-9+deb8u16) ...
Setting up libisccfg90 (1:9.9.5.dfsg-9+deb8u16) ...
Setting up libbind9-90 (1:9.9.5.dfsg-9+deb8u16) ...
Setting up liblwres90 (1:9.9.5.dfsg-9+deb8u16) ...
Setting up bind9-host (1:9.9.5.dfsg-9+deb8u16) ...
Setting up dnsutils (1:9.9.5.dfsg-9+deb8u16) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
 ---> b8f7c04cc933
Removing intermediate container 85403b684b48
Step 10/14 : RUN apt-get install -y postgresql-client-common
 ---> Running in eb3bfe20cd2a
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  lsb-release
Suggested packages:
  lsb
The following NEW packages will be installed:
  lsb-release postgresql-client-common
0 upgraded, 2 newly installed, 0 to remove and 73 not upgraded.
Need to get 100 kB of archives.
After this operation, 285 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main lsb-release all 4.1+Debian13+nmu1 [26.5 kB]
Get:2 http://deb.debian.org/debian/ jessie/main postgresql-client-common all 165+deb8u3 [73.8 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 100 kB in 1s (91.9 kB/s)
Selecting previously unselected package lsb-release.
(Reading database ... 23411 files and directories currently installed.)
Preparing to unpack .../lsb-release_4.1+Debian13+nmu1_all.deb ...
Unpacking lsb-release (4.1+Debian13+nmu1) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../postgresql-client-common_165+deb8u3_all.deb ...
Unpacking postgresql-client-common (165+deb8u3) ...
Setting up lsb-release (4.1+Debian13+nmu1) ...
Setting up postgresql-client-common (165+deb8u3) ...
 ---> ad80e4ef6c7c
Removing intermediate container eb3bfe20cd2a
Step 11/14 : RUN apt-get install -y postgresql-client-9.6
 ---> Running in 2a3ddfb5db74
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-client-9.6
E: Couldn't find any package by regex 'postgresql-client-9.6'
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get install -y postgresql-client-9.6' returned a non-zero code: 100

**Comment by rjunk** [comment]
For some reason your python:3 image is sourcing from jessie, but it should be sourcing stretch. No sure why that could be though.

**Comment by AdamLouis123456** [comment]
hey do you know how can i get the SSH key to login? i'm trapped in this annoying things

**Comment by darknight-007** [comment]
@AdamLouis123456 If you are involved with the Penn dev team, I can create an SSH account for you.

**Comment by darknight-007** [comment]
@harishanand95 So what's the fix?

**Comment by harishanand95** [comment]
The PR #8 I have made works fine with postgres-9.4. Wetty seems to be not working. I guess, it's an unrelated issue here
